### ISSUE TITLE
Unsubscribing 

### ISSUE THREAD

**Issue by nick-jonas** [paoloricciuti/sveltekit-search-params#3]
I noticed when I go to different page routes my search params are persisting, and I think it's because I need to `unsubscribe()` during an `onDestroy()` lifecycle hook.  Would you consider returning the subscription that you have [here](https://github.com/paoloricciuti/sveltekit-search-params/blob/master/src/lib/sveltekit-search-params.ts#L139)?

**Comment by nick-jonas** [comment]
Hmm maybe I'm doing something wrong.  I have this in a child component of a `+page.svelte`:

```
const languageQueryParam = queryParam(isSourceLang ? 'sl' : 'tl', {
		encode: (value) => value.language || 'auto',
		decode: async (value) => {
			console.log('this still triggers when the .svelte component it lives in is destroyed');
			// wait for all languages to be loaded before decoding
			await langsLoaded.load();
			// handle param for auto detect
			if (isSourceLang && (value === 'auto' || !value)) {
				$selectedSourceLang = { detect: true };
			}
			// set target language to default if it's not in the query param
			else if (!isSourceLang && !value) {
				$languageQueryParam = getLanguageObjFromId($defaultTargetLanguage.text);
			}
			// there is a value set in query param
			else if (value) {
				const paramLangObj = getLanguageObjFromId(value, isSourceLang);
				if (paramLangObj) {
					if (isSourceLang) {
						$selectedSourceLang = paramLangObj;
					} else {
						$selectedTargetLang = paramLangObj;
					}
				}
			}
		}
	});
```

When a navigation button is pressed and navigates away via `on:click={() => goto('/anotherpage', {invalidateAll: true})}`, the queryParam *stays* and the decode method still fires.

Do you have a recommended approach here?

**Comment by paoloricciuti** [comment]
Got it...yeah it's probably because you never unsubscribe from page. The proper fix tho should be overriding the subscribe function of the actual store to unsubscribe also from the page store. I'll try to handle this as soon as i can and push a fix.

**Comment by paoloricciuti** [comment]
It should be fixed in the 0.1.7 version...let me know if it's fixed on your side after an update.

Also regarding your code i think it has a couple of problems:

1. you are checking for isSourceLang while initializing the store but if that's a reactive variable the store will not be reinstantiated on change. It should either be put in a reactive statement or extrapolated in two different queryParam calls.
2. i would honestly avoid large async operations on decode since it's called pretty often. I don't know the specific case of your application but i would go ahead and stick that code in a reactive statement and read the value from the query params as is (as a string) while also using it in the reactive statement (so that it reruns whenever the query params change).

**Comment by paoloricciuti** [comment]
Mmm that seems strange...do you have a repo I can look at?

**Comment by paoloricciuti** [comment]
In the meantime if you want to take a look here's my small reproduction that doesn't seem to be affected from the bug you describe. Did you update to 0.1.7? Is there something you are doing differently?

https://stackblitz.com/edit/sveltejs-kit-template-default-jpgn4o

**Comment by paoloricciuti** [comment]
It actually run whenever the query params change. So even if something else is changing the query param it will rerun decode.

Btw I've tried your repro and it doesn't seems to log more than it should...can you provide a reproduction step list?

**Comment by nick-jonas** [comment]
Not exactly sure what I did, but somehow it's not happening in my app now!  Thanks for being timely and following this :)

**Comment by paoloricciuti** [comment]
> Not exactly sure what I did, but somehow it's not happening in my app now! Thanks for being timely and following this :)

It might have been some cache problem maybe. Glad it worked in the end and thank you for reporting the bug.
