### ISSUE TITLE
Error exporting compressToEncodedURIComponent

### ISSUE THREAD

**Issue by KarolusD** [paoloricciuti/sveltekit-search-params#7]
```
client-manifest.js:28 SyntaxError: The requested module '/node_modules/.pnpm/lz-string@1.4.4/node_modules/lz-string/libs/lz-string.js?v=2285ece9' does not provide an export named 'compressToEncodedURIComponent' (at sveltekit-search-params.js?v=2285ece9:7:10)
handleError @ client-manifest.js:28
```

using:
```
"@sveltejs/adapter-auto": "next",
"@sveltejs/kit": "1.0.0-next.561",
```

**Comment by KarolusD** [comment]
![image](https://user-images.githubusercontent.com/35146988/206560166-af43a587-00d0-405e-97c6-6c4dd37da96e.png)

also getting some warning when installing via pnpm

**Comment by paoloricciuti** [comment]
That's curious...I'll take a look as soon as I can

**Comment by sw-yx** [comment]
having the same issue 
![image](https://user-images.githubusercontent.com/6764957/206880186-c755277e-0a39-4b6f-95ad-b6e140084abe.png)

**Comment by paoloricciuti** [comment]
Mmm I wonder why I never had this problem...it should be because lz-string is commonjs and I'm importing as a module.

**Comment by paoloricciuti** [comment]
Ok as i've suspected it's a pnpm problem it seems...i'm debugging this right now if i'm successfull i'll publish a new version soon

**Comment by sw-yx** [comment]
thank you!

**Comment by sw-yx** [comment]
@paoloricciuti :( 
![image](https://user-images.githubusercontent.com/6764957/211224610-2e2e0182-7a7b-4521-b42b-752afa08e9de.png)

**Comment by paoloricciuti** [comment]
Wtf I didn't publish anything and lz-string did not publish either how is this all of a sudden broken? Is this a new project? Could this be a cache issue with pnpm?

**Comment by paoloricciuti** [comment]
@sw-yx this should hopefully be the last time we have this problem...i've decided to remove lz-string as a dependency and keep a slimmed down version of the library with the correct export in ESM (with proper attribution obviosuly).

Let me know if 0.1.13 fixes it for you (it does for me in local).

**Comment by sw-yx** [comment]
ty!

**Comment by sw-yx** [comment]
yes 0.1.13 seems to work now!

**Comment by paoloricciuti** [comment]
> ty! no its still my swyxkit project, and i was not using pnpm

it's absolutely crazy how it can randomly break. I guess it's because of this code inside lz-string

https://github.com/pieroxy/lz-string/blob/2f749bc9fe3cc889fa9e32d2769a930d977596e6/libs/lz-string.js#L497-506

which does some crazy things. Overall i'll gladly take care of it in an extra file inside my codebase especially since lz-string was last published 8 years ago

Closing this issue now.
