### ISSUE TITLE
Value is nullable if default value is provided

### ISSUE THREAD

**Issue by olehmisar** [paoloricciuti/sveltekit-search-params#75]
### Describe the bug

<img width="391" alt="image" src="https://github.com/paoloricciuti/sveltekit-search-params/assets/29802592/29ea0182-6fa3-4c59-a7dd-a6bae9df9d89">

type of `page` should be `Writable<number>`

### Reproduction

```svelte
<script>
  import { queryParam, ssp } from "sveltekit-search-params";

  $: page = queryParam("p", ssp.number());
</script>
```

**Comment by paoloricciuti** [comment]
I've tried and failed to make this work...but if you can I'll enjoy this enhancement 😁
