### ISSUE TITLE
Remove the query string from the URL when a parameter isn't set

### ISSUE THREAD

**Issue by mikenikles** [paoloricciuti/sveltekit-search-params#77]
### Describe the problem

I have a `search` query string parameter bound to a search input field. Ideally, when the search input field is empty, I'd like to see the `search` query string disappear from the URL. Currently, it shows `?search=`.

### Describe the proposed solution

The current solution is this:

```ts
function nullableQueryParam<T>({
  encode,
  ...codec
}: EncodeAndDecodeOptions<T>) {
  return {
    ...codec,
    encode(value) {
      if (value === "") return undefined;
      if (Array.isArray(value) && value.length === 0) return undefined;

      return encode(value);
    },
  } as EncodeAndDecodeOptions<T>;
}
```

Then use it as follows:

```ts
export function getUrlSearchParamsFiltersStore() {
  return queryParam<string[]>("filters", nullableQueryParam(ssp.array()));
}
```

**Comment by paoloricciuti** [comment]
The problem I see with this is that technically when the search param is not there the value is `null`. In some occasions having it disappear would be good in other would be bad.

However there is a better solution: you can use the default of '' and set `showDefaults` to false

```svelte
<script lang="ts">
	import { queryParam, ssp } from 'sveltekit-search-params';

	const search = queryParam('search', ssp.number(''), {
		showDefaults: false,
	});
</script>
```

**Comment by mikenikles** [comment]
Oh, very elegant. I missed that in the release notes 😊.
