### ISSUE TITLE
Store is not cleared when navigating to the same route without params

### ISSUE THREAD

**Issue by rschyboll** [paoloricciuti/sveltekit-search-params#86]
### Describe the bug

I've encountered an issue when using `queryParam` with an object or array. When navigating to the same route without the search parameters, the store does not update. Instead, it retains the previous query parameters, rather than resetting to the default values.

### Reproduction

I've managed to create a simplified example that demonstrates the issue:
https://stackblitz.com/edit/sveltejs-kit-template-default-8jz3kw?file=src%2Froutes%2Fprojects%2F%2Bpage.svelte

To replicate:
1. Open the "Projects" page in the navbar. 
2. Enter some data through the input field. The entered data should be present in the URL as an object in search params.
3. Click again on the "Projects" link in the navbar. 

The issue seems to not occur when using primitive values.

**Comment by paoloricciuti** [comment]
Thanks for reporting, I will check probably tomorrow 🤟🏻

**Comment by paoloricciuti** [comment]
Should be fixed now, you can try install v3

**Comment by rschyboll** [comment]
I just tested it, and it seems to be working correctly. Thank you very much :smile:

**Comment by paoloricciuti** [comment]
> I just tested it, and it seems to be working correctly. Thank you very much 😄

Thank you for reporting
